########服务端口定义############
server:
  port: 1001
########eureka配置############
eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://eureka-second:10001/eureka/

########redis配置############
spring:
  redis:
    database: 0             # Redis数据库索引
    host: localhost         # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password: cloud_redis  # Redis服务器连接密码（默认为空）
    pool:
      max-active: 200     # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1        # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8         # 连接池中的最大空闲连接
      min-idle: 0         # 连接池中的最小空闲连接
    timeout: 0            # 连接超时时间（毫秒）
